### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by jedsmith13** [sayeko/angular4-ngrx-upload-module#5]
@sayeko Are you still maintaining this? I have made several pull requests, one as far back as 21 days ago and I am wondering if this is something you are planning on doing anything with as I haven't seen any responses to know if you are okay with my changes or not.

Thanks for the work you have done on this by the way I am using it internally as a module and would like to see some progress made on having it as a regular module on NPM. I could help you get it there if you are too busy at the moment to do it all yourself.

**Comment by sayeko** [comment]
Hi @jedsmith13 glad to hear that my module helped you and you use it.
I currently too busy to work on this module and also keep up with angular + ngrx, rxjs changes.
you are more than welcome to add your changes so other could enjoy of updated drag and drop module.

maybe in the near future I will add several changes.

**Comment by jedsmith13** [comment]
@sayeko Glad to hear it isn't abandoned. I will continue to add pull-requests as I make changes.

Would you be interested in me getting it set so you can create it as an NPM module?

**Comment by sayeko** [comment]
@jedsmith13 Yes it could be awesome.

**Comment by jedsmith13** [comment]
@sayeko I will see about making those changes and creating a pull request this week or next, but in the meantime, I will close this issue.
